# Generated by Django 3.0.2 on 2020-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0003_auto_20200608_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(default='title', max_length=40),
        ),
    ]
